# Generated by Django 3.0.7 on 2020-07-27 14:55

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('headline', models.CharField(max_length=1000)),
                ('image', models.FileField(upload_to='')),
                ('text', models.TextField()),
                ('date', models.DateField()),
                ('author', models.CharField(max_length=100)),
                ('website', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='ScientificArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('date', models.DateField()),
                ('author', models.CharField(max_length=100)),
                ('publication', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(default=20)),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('smoking', models.CharField(choices=[('CURRENT', 'Current Smoker'), ('FORMER', 'Former Smoker'), ('NEVER', 'Never Smoker')], default='NEVER', max_length=10)),
                ('drinking', models.CharField(choices=[('CURRENT', 'Current Drinker'), ('FORMER', 'Former Drinker'), ('NEGATIVE', 'Never Drank')], default='NEVER', max_length=10)),
                ('housing', models.CharField(choices=[('ALONE', 'Live Alone'), ('GROUP', 'Live With Others')], default='ALONE', max_length=10)),
                ('marital', models.CharField(choices=[('SINGLE', 'Single'), ('MARRIED', 'Married'), ('OTHER', 'Other')], default='ALONE', max_length=10)),
                ('insurance', models.CharField(choices=[('UNINSURED', 'UnInsured'), ('INSURED', 'Insured')], default='UNINSURED', max_length=10)),
                ('employment', models.CharField(choices=[('EMPLOYED', 'Employed'), ('UNEMPLOYED', 'Unemployed')], default='INSURED', max_length=10)),
                ('diet', models.CharField(choices=[('VEGAN', 'Vegan'), ('VEGETARIAN', 'Vegetarian'), ('REGULAR', 'Regular')], default='REGULAR', max_length=10)),
                ('veteran', models.CharField(choices=[('NOT', 'Not A Veteran'), ('VETERAN', 'Veteran')], default='NOT', max_length=10)),
                ('disabilities', models.CharField(choices=[('DISABLE', 'Disabled'), ('ABLE', 'Able')], default='ABLE', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CovidTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('type', models.CharField(choices=[('ANTIBODY', 'Antibody Testing'), ('ANTIGEN', 'Antigen Testing')], default='ANTIBODY', max_length=10)),
                ('results', models.CharField(choices=[('UNKNOWN', 'Unknown'), ('NEGATIVE', 'Negative'), ('POSITIVE', 'Positive')], default='UNKNOWN', max_length=10)),
                ('hospitalization', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='NO', max_length=10)),
                ('ventilation', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='NO', max_length=10)),
                ('medication', models.CharField(choices=[('HCQ', 'Hydroxychloroquine')], default='HCQ', max_length=30)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Patient')),
            ],
        ),
    ]
