# Generated by Django 3.0.7 on 2020-12-07 02:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conditions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptionCondition', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='ConditionsHelped',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptionConditionHelped', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='ConditionsHelped2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptionConditionHelped', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='DemographicAffected',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptionDemo', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateEnrolled', models.DateField()),
                ('insuranceType', models.CharField(choices=[('MEDICARE', 'Medicare'), ('MEDICAID', 'Medicaid'), ('PRIVATE HEALTH PROGRAMS', 'Private Health Programs'), ('OTHER', 'Other'), ('NONE', 'None')], default='NONE', max_length=100)),
                ('insuranceBrand', models.TextField()),
                ('insurancePlan', models.CharField(choices=[('HMO', 'HMO'), ('PPO', 'PPO'), ('EPO', 'EPO'), ('POS', 'POS'), ('HDHP', 'HDHO'), ('NONE', 'None')], default='NONE', max_length=100)),
                ('carePlan', models.CharField(choices=[('DIABETES CARE PLAN', 'Diabetes care plan'), ('ALLERGIC DISORDER MONITORING', 'Allergic disorder monitoring'), ('ANTI-SUICIDE PSYCHOTHERAPY', 'Anti-suicide psychotherapy'), ('ASTHMA SELF MANAGEMENT', 'Asthma self management'), ('BURN CARE', 'Burn care'), ('CANCER CARE PLAN', 'Cancer care plan'), ('CHRONIC OBSTRUCTIVE PULMONARY DISEASE', 'Chronic obstructive pulmonary disease '), ('DEMENTIA MANAGEMENT', 'Dementia management'), ('DIABETES SELF MANAGEMENT PLAN', 'Diabetes self management plan'), ('DIALYSIS CARE PLAN', 'Dialysis care plan'), ('FRACTURE CARE', 'Fracture care'), ('HEAD INJURY REHABILITATION', 'Head injury rehabilitation'), ('HEART FAILURE SELF MANAGEMENT PLAN', 'Heart failure self management plan'), ('HYPERLIPIDEMIA CLINICAL MANAGEMENT PLAN', 'Hyperlipidemia clinical management plan'), ('INFECTIOUS DISEASE CARE PLAN', 'Infectious disease care plan'), ('INPATIENT CARE PLAN', 'Inpatient care plan'), ('LIFESTYLE EDUCATION REGARDING HYPERTENSION', 'Lifestyle education regarding hypertension'), ('MAJOR DEPRESSIVE DISORDER CLINICAL MANAGEMENT PLAN', 'Major depressive disorder clinical management plan'), ('MAJOR SURGERY CARE MANAGEMENT', 'Major surgery care management'), ('MENTAL HEALTH CARE PLAN', 'Mental health care plan'), ('MINOR SURGERY CARE MANAGEMENT', 'Minor surgery care management'), ('MUSCULOSKELETAL CARE', 'Musculoskeletal care'), ('OVERACTIVITY/INATTENTION BEHAVIOR MANAGEMENT', 'Overactivity/inattention behavior management'), ('PHYSICAL THERAPY PROCEDURE', 'Physical therapy procedure'), ('POSTOPERATIVE CARE', 'Postoperative care'), ('PSYCHIATRY CARE PLAN', 'Psychiatry care plan'), ('RESPIRATORY THERAPY', 'Respiratory therapy'), ('ROUTINE ANTENATAL CARE', 'Routine antenatal care'), ('SELF-CARE INTERVENTIONS', 'Self-care interventions'), ('SKIN CONDITION CARE', 'Skin condition care'), ('SPINAL CORD INJURY REHABILITATION', 'Spinal cord injury rehabilitation'), ('TERMINAL CARE', 'Terminal care'), ('URINARY TRACT INFECTION CARE', 'Urinary tract infection care'), ('WOUND CARE', 'Wound care'), ('OTHER', 'Other')], default='NONE', max_length=200)),
                ('carePlanOther', models.TextField()),
                ('annualMedicalBill', models.TextField()),
                ('annualInsuranceBill', models.TextField()),
                ('healthInsurance', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='NO', max_length=10)),
                ('userComment', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Modalities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptionModality', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='ModalityResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articleLink', models.CharField(max_length=1000)),
                ('articleImage', models.CharField(default='https://static.thenounproject.com/png/3255444-200.png', max_length=1000)),
                ('title', models.CharField(max_length=1000)),
                ('description', models.TextField()),
                ('publishDate', models.DateField(default=django.utils.timezone.now)),
                ('goal', models.CharField(max_length=1000)),
                ('typeArticle', models.CharField(max_length=1000)),
                ('patientReadScore', models.IntegerField()),
                ('patientPhysicalScore', models.IntegerField()),
                ('patientMoodScore', models.IntegerField()),
                ('timeRequired', models.IntegerField()),
                ('conditions', models.ManyToManyField(to='main.Conditions')),
                ('conditionsHelped', models.ManyToManyField(to='main.ConditionsHelped')),
                ('demographicAffected', models.ManyToManyField(to='main.DemographicAffected')),
                ('modalities', models.ManyToManyField(to='main.Modalities')),
            ],
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('headline', models.CharField(max_length=1000)),
                ('image', models.FileField(upload_to='')),
                ('text', models.TextField()),
                ('date', models.DateField()),
                ('author', models.CharField(max_length=100)),
                ('website', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userTransferID', models.IntegerField(default=0)),
                ('age', models.IntegerField(default=20)),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('smoking', models.CharField(choices=[('CURRENT', 'Current Smoker'), ('FORMER', 'Former Smoker'), ('NEVER', 'Never Smoker')], default='NEVER', max_length=10)),
                ('drinking', models.CharField(choices=[('CURRENT', 'Current Drinker'), ('FORMER', 'Former Drinker'), ('NEGATIVE', 'Never Drank')], default='NEVER', max_length=10)),
                ('housing', models.CharField(choices=[('ALONE', 'Live Alone'), ('GROUP', 'Live With Others')], default='ALONE', max_length=10)),
                ('marital', models.CharField(choices=[('SINGLE', 'Single'), ('MARRIED', 'Married'), ('OTHER', 'Other')], default='ALONE', max_length=10)),
                ('employment', models.CharField(choices=[('EMPLOYED', 'Employed'), ('UNEMPLOYED', 'Unemployed')], default='INSURED', max_length=10)),
                ('diet', models.CharField(choices=[('VEGAN', 'Vegan'), ('VEGETARIAN', 'Vegetarian'), ('REGULAR', 'Regular')], default='REGULAR', max_length=10)),
                ('veteran', models.CharField(choices=[('NOT', 'Not A Veteran'), ('VETERAN', 'Veteran')], default='NOT', max_length=10)),
                ('disabilities', models.CharField(choices=[('DISABLE', 'Disabled'), ('ABLE', 'Able')], default='ABLE', max_length=10)),
                ('dateEnrolled', models.DateField(default=django.utils.timezone.now)),
                ('firstName', models.TextField(default='John')),
                ('lastName', models.TextField(default='Smith')),
                ('phoneNumber', models.IntegerField(default=1111111111)),
                ('email', models.TextField(default='abc@email.com', help_text='Enter in correct format abc@email.com')),
                ('dateOfBirth', models.DateField(default=django.utils.timezone.now)),
                ('ethnicity', models.TextField(default='Not Reported')),
                ('race', models.TextField(default='Not Reported')),
                ('gender', models.CharField(choices=[('FEMALE', 'Female'), ('MALE', 'Male'), ('OTHER', 'Other'), ('PREFER NOT TO DISCLOSE', 'Prefer Not To Disclose')], default='OTHER', max_length=25)),
                ('givenBirth', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='NO', max_length=10)),
                ('timesBirth', models.PositiveIntegerField(default=0)),
                ('exercise', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='NO', max_length=10)),
                ('allergies', models.TextField(default='None')),
                ('userComment', models.CharField(default='None', max_length=1000)),
                ('searchRange', models.IntegerField(default=10)),
                ('ModalitiesBookmarked', models.ManyToManyField(related_name='_patient_ModalitiesBookmarked_+', to='main.ModalityResource')),
                ('ModalitiesWatched', models.ManyToManyField(related_name='_patient_ModalitiesWatched_+', to='main.ModalityResource')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScientificArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('date', models.DateField()),
                ('author', models.CharField(max_length=100)),
                ('publication', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sensors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usingSensors', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='NO', max_length=10)),
                ('reasonUsing', models.CharField(choices=[('SYMPTOM MANAGEMENT DOCTOR REQUIREMENT', 'Symptom Management Doctor Requirement'), ('TREATMENT DOCTOR REQUIREMENT', 'Treatment Doctor Requirement'), ('SYMPTOM MANAGEMENT PERSONAL INTEREST', 'Symptom Management Personal Interest'), ('TREATMENT PERSONAL INTEREST', 'Treatment Personal Interest'), ('DAILY ACTIVITY MANAGEMENT', 'Daily Activity Management'), ('EDUCATION', 'Education'), ('OTHER', 'Other')], default='OTHER', max_length=100)),
                ('moreInformation', models.CharField(max_length=1000)),
                ('brandName', models.CharField(max_length=1000)),
                ('sharingData', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='NO', max_length=10)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Payer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corporationName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('applicationId', models.IntegerField()),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('insurance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Insurance')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Patient')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalPhenotype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.CharField(choices=[('CARDIOVASCULAR DISEASE', 'Cardiovascular Disease'), ('NEUROLOGICAL DISEASE', 'Neurological Disease'), ('CANCER', 'Cancer'), ('RESPIRATORY DISEASE', 'Respiratory Disease'), ('METABOLIC DISEASE', 'Metabolic Disease'), ('IMMUNOLOGICAL DISEASE', 'Immunological Disease'), ('HEMATOLOGICAL DISEASE', 'Hematological Disease'), ('MENTAL DISEASE', 'Mental Disease'), ('INFECTIOUS DISEASE', 'Infectious Disease'), ('GASTROINTESTINAL DISEASE', 'Gastrointestinal Disease'), ('ENDOCRINE SYSTEM DISEASE', 'Endocrine System Disease'), ('REPRODUCTIVE SYSTEM DISEASE', 'Reproductive System Disease'), ('URINARY SYSTEM DISEASE', 'Urinary System Disease'), ('GENETIC DISEASE', 'Genetic Disease'), ('SYNDROME', 'Syndrome'), ('OTHERS', 'Others')], default='NONE', max_length=60)),
                ('cardioDisease', models.CharField(max_length=1000)),
                ('cardioMedication', models.CharField(max_length=1000)),
                ('neurologicalInfo', models.CharField(max_length=1000)),
                ('neurologicalMedication', models.CharField(max_length=1000)),
                ('medicationList', models.CharField(max_length=1000)),
                ('vaccinationList', models.CharField(choices=[('INFLUENZA', 'Influenza'), ('TD', 'Td'), ('HEP B', 'Hep B'), ('MENINGOCOCCAL MCV4P', 'Meningococcal MCV4P'), ('HEP A', 'Hep A'), ('PNEUMOCOCCAL CONJUGATE PCV 13', 'Pneumococcal conjugate PCV 13'), ('ZOSTER', 'Zoster'), ('PNEUMOCOCCAL POLYSACCHARIDE', 'Pneumococcal Polysaccharide'), ('VALENT', 'Valent'), ('HIB', 'Hib'), ('IPV', 'IPV'), ('VARICELLA', 'varicella'), ('MMR', 'MMR'), ('TDAP', 'Tdap'), ('HPV', 'HPV'), ('HEP A', 'Hep A'), ('DTAP', 'DTaP')], default='OTHER', max_length=200)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Patient')),
            ],
        ),
        migrations.AddField(
            model_name='insurance',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Patient'),
        ),
        migrations.CreateModel(
            name='CovidTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('type', models.CharField(choices=[('ANTIBODY', 'Antibody Testing'), ('ANTIGEN', 'Antigen Testing')], default='ANTIBODY', max_length=10)),
                ('results', models.CharField(choices=[('UNKNOWN', 'Unknown'), ('NEGATIVE', 'Negative'), ('POSITIVE', 'Positive')], default='UNKNOWN', max_length=10)),
                ('hospitalization', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='NO', max_length=10)),
                ('ventilation', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='NO', max_length=10)),
                ('medication', models.CharField(choices=[('REMDESIVIR', 'Remdesivir'), ('DEXAMETHASONE', 'Dexamethasone'), ('HYDROXYCHLOROQUINE', 'Hydroxychloroquine'), ('AZITHROMYCIN', 'Azithromycin'), ('CONVALESCENT PLASMA', 'Convalescent plasma'), ('ACTEMRA', 'Actemra'), ('KALETRA', 'Kaletra'), ('TAMIFLU', 'Tamiflu'), ('AVIGAN', 'Avigan'), ('COLCRYS', 'Colcrys'), ('IVERMECTIN', 'Ivermectin')], default='OTHERS', max_length=60)),
                ('covidStatus', models.CharField(choices=[('CURRENTLY POSITIVE', 'Currently Positive'), ('CURRENTLY NEGATIVE', 'Currently Negative'), ('CURRENTLY NEGATIVE, WAS POSITIVE', 'Currently Negative, Was Positive'), ('NOT TESTED', 'Not tested'), ('PREFER NOT TO TELL', 'Prefer not to tell')], default='NONE', max_length=50)),
                ('otherIntervention', models.CharField(choices=[('BEHAVIOR', 'Behavior'), ('NUTRITION', 'Nutrition'), ('OTHERS', 'Others')], default='NONE', max_length=10)),
                ('covidMedicineOthers', models.CharField(max_length=200)),
                ('behaviorIntervention', models.CharField(max_length=1000)),
                ('nutritionIntervention', models.CharField(max_length=1000)),
                ('dateDischarge', models.DateField()),
                ('dateRecovery', models.DateField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Patient')),
            ],
        ),
    ]
