# Generated by Django 3.0.7 on 2020-10-27 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', 'migration15'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='ModalitiesBookmarked',
            field=models.ManyToManyField(related_name='_patient_ModalitiesBookmarked_+', to='main.ModalityResource'),
        ),
        migrations.AddField(
            model_name='patient',
            name='ModalitiesWatched',
            field=models.ManyToManyField(related_name='_patient_ModalitiesWatched_+', to='main.ModalityResource'),
        ),
    ]
