# Generated by Django 3.0.7 on 2020-07-27 17:45

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default='POINT(-96.876369 29.905320)', srid=4326),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='searchRange',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
