# Generated by Django 3.0.7 on 2020-07-22 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('headline', models.CharField(max_length=1000)),
                ('image', models.FileField(upload_to='')),
                ('text', models.TextField()),
                ('date', models.DateField()),
                ('author', models.CharField(max_length=100)),
                ('website', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ScientificArticles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('date', models.DateField()),
                ('author', models.CharField(max_length=100)),
                ('publication', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='patient',
            name='status',
            field=models.CharField(choices=[('BLOOD', 'Antibody Testing'), ('SWAB', 'Neonatal Nasopharyngeal Swabs')], max_length=10),
        ),
    ]
