# Generated by Django 3.0.7 on 2020-12-21 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_payer_usertransferid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payer',
            name='insurance',
        ),
        migrations.RemoveField(
            model_name='payer',
            name='patient',
        ),
        migrations.AddField(
            model_name='insurance',
            name='payer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.Payer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='corporationName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Payer'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='ModalitiesBookmarked',
            field=models.ManyToManyField(blank=True, null=True, related_name='_patient_ModalitiesBookmarked_+', to='main.ModalityResource'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='ModalitiesWatched',
            field=models.ManyToManyField(blank=True, null=True, related_name='_patient_ModalitiesWatched_+', to='main.ModalityResource'),
        ),
    ]
