# Generated by Django 3.0.7 on 2020-07-22 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200722_0304'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='tested',
            field=models.CharField(choices=[('BLOOD', 'Antibody Testing'), ('SWAB', 'Neonatal Nasopharyngeal Swabs')], default='BLOOD', max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='status',
            field=models.CharField(choices=[('NA', 'NA'), ('UNKNOWN', 'Unknown'), ('NEGATIVE', 'Negative'), ('POSITIVE', 'Positive'), ('RECOVERED', 'Recovered')], default='NA', max_length=10),
        ),
    ]
