# Generated by Django 3.0.7 on 2020-07-22 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200722_0312'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ScientificArticles',
            new_name='ScientificArticle',
        ),
    ]
