# Generated by Django 3.0.7 on 2020-08-24 17:10

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200824_0154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='city',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='state',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='street',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='zipCode',
        ),
        migrations.AddField(
            model_name='patient',
            name='userTransferID',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='covidtest',
            name='covidStatus',
            field=models.CharField(choices=[('CURRENTLY POSITIVE', 'Currently Positive'), ('CURRENTLY NEGATIVE', 'Currently Negative'), ('CURRENTLY NEGATIVE, WAS POSITIVE', 'Currently Negative, Was Positive'), ('NOT TESTED', 'Not tested'), ('PREFER NOT TO TELL', 'Prefer not to tell')], default='NONE', max_length=50),
        ),
        migrations.AlterField(
            model_name='covidtest',
            name='otherIntervention',
            field=models.CharField(choices=[('BEHAVIOR', 'Behavior'), ('NUTRITION', 'Nutrition'), ('OTHERS', 'Others')], default='NONE', max_length=10),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='carePlan',
            field=models.CharField(choices=[('DIABETES CARE PLAN', 'Diabetes care plan'), ('ALLERGIC DISORDER MONITORING', 'Allergic disorder monitoring'), ('ANTI-SUICIDE PSYCHOTHERAPY', 'Anti-suicide psychotherapy'), ('ASTHMA SELF MANAGEMENT', 'Asthma self management'), ('BURN CARE', 'Burn care'), ('CANCER CARE PLAN', 'Cancer care plan'), ('CHRONIC OBSTRUCTIVE PULMONARY DISEASE', 'Chronic obstructive pulmonary disease '), ('DEMENTIA MANAGEMENT', 'Dementia management'), ('DIABETES SELF MANAGEMENT PLAN', 'Diabetes self management plan'), ('DIALYSIS CARE PLAN', 'Dialysis care plan'), ('FRACTURE CARE', 'Fracture care'), ('HEAD INJURY REHABILITATION', 'Head injury rehabilitation'), ('HEART FAILURE SELF MANAGEMENT PLAN', 'Heart failure self management plan'), ('HYPERLIPIDEMIA CLINICAL MANAGEMENT PLAN', 'Hyperlipidemia clinical management plan'), ('INFECTIOUS DISEASE CARE PLAN', 'Infectious disease care plan'), ('INPATIENT CARE PLAN', 'Inpatient care plan'), ('LIFESTYLE EDUCATION REGARDING HYPERTENSION', 'Lifestyle education regarding hypertension'), ('MAJOR DEPRESSIVE DISORDER CLINICAL MANAGEMENT PLAN', 'Major depressive disorder clinical management plan'), ('MAJOR SURGERY CARE MANAGEMENT', 'Major surgery care management'), ('MENTAL HEALTH CARE PLAN', 'Mental health care plan'), ('MINOR SURGERY CARE MANAGEMENT', 'Minor surgery care management'), ('MUSCULOSKELETAL CARE', 'Musculoskeletal care'), ('OVERACTIVITY/INATTENTION BEHAVIOR MANAGEMENT', 'Overactivity/inattention behavior management'), ('PHYSICAL THERAPY PROCEDURE', 'Physical therapy procedure'), ('POSTOPERATIVE CARE', 'Postoperative care'), ('PSYCHIATRY CARE PLAN', 'Psychiatry care plan'), ('RESPIRATORY THERAPY', 'Respiratory therapy'), ('ROUTINE ANTENATAL CARE', 'Routine antenatal care'), ('SELF-CARE INTERVENTIONS', 'Self-care interventions'), ('SKIN CONDITION CARE', 'Skin condition care'), ('SPINAL CORD INJURY REHABILITATION', 'Spinal cord injury rehabilitation'), ('TERMINAL CARE', 'Terminal care'), ('URINARY TRACT INFECTION CARE', 'Urinary tract infection care'), ('WOUND CARE', 'Wound care'), ('OTHER', 'Other')], default='NONE', max_length=200),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='insurancePlan',
            field=models.CharField(choices=[('HMO', 'HMO'), ('PPO', 'PPO'), ('EPO', 'EPO'), ('POS', 'POS'), ('HDHP', 'HDHO'), ('NONE', 'None')], default='NONE', max_length=100),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='insuranceType',
            field=models.CharField(choices=[('MEDICARE', 'Medicare'), ('MEDICAID', 'Medicaid'), ('PRIVATE HEALTH PROGRAMS', 'Private Health Programs'), ('OTHER', 'Other'), ('NONE', 'None')], default='NONE', max_length=100),
        ),
        migrations.AlterField(
            model_name='medicalphenotype',
            name='problem',
            field=models.CharField(choices=[('CARDIOVASCULAR DISEASE', 'Cardiovascular Disease'), ('NEUROLOGICAL DISEASE', 'Neurological Disease'), ('CANCER', 'Cancer'), ('RESPIRATORY DISEASE', 'Respiratory Disease'), ('METABOLIC DISEASE', 'Metabolic Disease'), ('IMMUNOLOGICAL DISEASE', 'Immunological Disease'), ('HEMATOLOGICAL DISEASE', 'Hematological Disease'), ('MENTAL DISEASE', 'Mental Disease'), ('INFECTIOUS DISEASE', 'Infectious Disease'), ('GASTROINTESTINAL DISEASE', 'Gastrointestinal Disease'), ('ENDOCRINE SYSTEM DISEASE', 'Endocrine System Disease'), ('REPRODUCTIVE SYSTEM DISEASE', 'Reproductive System Disease'), ('URINARY SYSTEM DISEASE', 'Urinary System Disease'), ('GENETIC DISEASE', 'Genetic Disease'), ('SYNDROME', 'Syndrome'), ('OTHERS', 'Others')], default='NONE', max_length=60),
        ),
        migrations.AlterField(
            model_name='patient',
            name='allergies',
            field=models.TextField(default='None'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0, 0), srid=4326),
        ),
        migrations.AlterField(
            model_name='patient',
            name='searchRange',
            field=models.IntegerField(default=10),
        ),
    ]
