# Generated by Django 3.0.7 on 2020-12-21 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201221_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurance',
            name='payer',
        ),
    ]
