# Generated by Django 3.0.7 on 2020-07-23 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200722_0317'),
    ]

    operations = [
        migrations.CreateModel(
            name='CovidTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('type', models.CharField(choices=[('ANTIBODY', 'Antibody Testing'), ('ANTIGEN', 'Antigen Testing')], default='ANTIBODY', max_length=10)),
                ('results', models.CharField(choices=[('UNKNOWN', 'Unknown'), ('NEGATIVE', 'Negative'), ('POSITIVE', 'Positive')], default='UNKNOWN', max_length=10)),
                ('hospitalization', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='NO', max_length=10)),
                ('ventilation', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='NO', max_length=10)),
                ('medication', models.CharField(choices=[('HCQ', 'Hydroxychloroquine')], default='HCQ', max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='patient',
            name='status',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='tested',
        ),
        migrations.AddField(
            model_name='patient',
            name='age',
            field=models.IntegerField(default=69),
        ),
        migrations.AddField(
            model_name='patient',
            name='diet',
            field=models.CharField(choices=[('VEGAN', 'Vegan'), ('VEGETARIAN', 'Vegetarian'), ('REGULAR', 'Regular')], default='REGULAR', max_length=10),
        ),
        migrations.AddField(
            model_name='patient',
            name='disabilities',
            field=models.CharField(choices=[('DISABLE', 'Disabled'), ('ABLE', 'Able')], default='ABLE', max_length=10),
        ),
        migrations.AddField(
            model_name='patient',
            name='drinking',
            field=models.CharField(choices=[('CURRENT', 'Current Smoker'), ('FORMER', 'Former Smoker'), ('NEGATIVE', 'Never Smoker')], default='NEVER', max_length=10),
        ),
        migrations.AddField(
            model_name='patient',
            name='employment',
            field=models.CharField(choices=[('EMPLOYED', 'Employed'), ('UNEMPLOYED', 'UnEmployed')], default='INSURED', max_length=10),
        ),
        migrations.AddField(
            model_name='patient',
            name='height',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='housing',
            field=models.CharField(choices=[('ALONE', 'Live Alone'), ('GROUP', 'Live With Others')], default='ALONE', max_length=10),
        ),
        migrations.AddField(
            model_name='patient',
            name='insurance',
            field=models.CharField(choices=[('UNINSURED', 'UnInsured'), ('INSURED', 'Insured')], default='UNINSURED', max_length=10),
        ),
        migrations.AddField(
            model_name='patient',
            name='martial',
            field=models.CharField(choices=[('SINGLE', 'Single'), ('MARRIED', 'Married')], default='ALONE', max_length=10),
        ),
        migrations.AddField(
            model_name='patient',
            name='smoking',
            field=models.CharField(choices=[('CURRENT', 'Current Smoker'), ('FORMER', 'Former Smoker'), ('NEVER', 'Never Smoker')], default='NEVER', max_length=10),
        ),
        migrations.AddField(
            model_name='patient',
            name='veteran',
            field=models.CharField(choices=[('NOT', 'Not A Veteran'), ('FORMER', 'Former Veteran'), ('CURRENT', 'Current Veteran')], default='NOT', max_length=10),
        ),
        migrations.AddField(
            model_name='patient',
            name='weight',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='covidTests',
            field=models.ForeignKey(default='?', on_delete=django.db.models.deletion.CASCADE, to='main.CovidTest'),
            preserve_default=False,
        ),
    ]
