# Generated by Django 3.0.7 on 2020-07-23 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200723_0352'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='covidTests',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.CovidTest'),
            preserve_default=False,
        ),
    ]
