# Generated by Django 3.0.7 on 2020-08-24 17:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200824_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='dateEnrolled',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='patient',
            name='dateOfBirth',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
