# Generated by Django 3.0.7 on 2020-07-23 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_patient_covidtests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='covidTests',
        ),
        migrations.AddField(
            model_name='covidtest',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Patient'),
            preserve_default=False,
        ),
    ]
