# Generated by Django 3.0.7 on 2020-08-24 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200824_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='phoneNumber',
            field=models.IntegerField(default=1111111111),
        ),
    ]
