# Generated by Django 3.0.7 on 2020-07-23 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200723_0418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='drinking',
            field=models.CharField(choices=[('CURRENT', 'Current Drinker'), ('FORMER', 'Former Drinker'), ('NEGATIVE', 'Never Drank')], default='NEVER', max_length=10),
        ),
    ]
