# Generated by Django 3.0.7 on 2020-08-24 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200824_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='timesBirth',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
