# Generated by Django 3.0.7 on 2020-08-24 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200824_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='userTransferID',
            field=models.IntegerField(default=0),
        ),
    ]
