# Generated by Django 3.0.7 on 2020-08-31 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200824_1736'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='location',
            new_name='currentPos',
        ),
    ]
