# Generated by Django 3.0.7 on 2020-09-24 22:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20200831_1257'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conditions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptionCondition', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='ConditionsHelped',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptionConditionHelped', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='DemographicAffected',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptionDemo', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Modalities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptionModality', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='ModalityResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articleLink', models.CharField(max_length=1000)),
                ('title', models.CharField(max_length=1000)),
                ('description', models.TextField()),
                ('publishDate', models.DateField(default=django.utils.timezone.now)),
                ('goal', models.CharField(max_length=1000)),
                ('typeArticle', models.CharField(max_length=1000)),
                ('patientReadScore', models.IntegerField()),
                ('patientPhysicalScore', models.IntegerField()),
                ('patientMoodScore', models.IntegerField()),
                ('timeRequired', models.IntegerField()),
                ('conditions', models.ManyToManyField(to='main.Conditions')),
                ('conditionsHelped', models.ManyToManyField(to='main.ConditionsHelped')),
                ('demographicAffected', models.ManyToManyField(to='main.DemographicAffected')),
                ('modalities', models.ManyToManyField(to='main.Modalities')),
            ],
        ),
    ]
