# Generated by Django 3.0.7 on 2020-09-24 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_conditions_conditionshelped_demographicaffected_modalities_modalityresource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conditions',
            name='descriptionCondition',
            field=models.CharField(max_length=100),
        ),
    ]
