# Generated by Django 3.0.7 on 2020-09-24 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20200924_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conditions',
            name='descriptionCondition',
            field=models.CharField(max_length=1000),
        ),
    ]
