# Generated by Django 3.0.7 on 2020-09-24 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20200924_2240'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConditionsHelped2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptionConditionHelped', models.CharField(max_length=1000)),
            ],
        ),
    ]
